const productsList = [
    {
      id_product: 1,
      category: "nacional",
      fk_idcategorys: 1,
      name_product: "Grêmio /22",
      price: 149.99,
      image: "/images/produtos/gremio22.jpg",
      id_categorys: 1,
      name_categorys: "Clubes brasileiros",
      selected: false
    },
    {
      id_product: 2,
      category: "nacional",
      fk_idcategorys: 1,
      name_product: "Inter /22",
      price: 280,
      image: "./images/produtos/inter22.jpg",
      id_categorys: 1,
      name_categorys: "Clubes brasileiros",
      selected: false
    },
    {
      id_product: 9,
      category: "nacional",
      fk_idcategorys: 1,
      name_product: "Cruzeiro /22",
      price: 299.99,
      image: "./images/produtos/Cruzeiro22.jpg",
      id_categorys: 1,
      name_categorys: "Clubes brasileiros",
      selected: false
    },
    {
      id_product: 4,
      category: "nacional",
      fk_idcategorys: 1,
      name_product: "Vasco /22",
      price: 289.99,
      image: "./images/produtos/vasco22.jpg",
      id_categorys: 1,
      name_categorys: "Clubes brasileiros",
      selected: false
    },
    {
      id_product: 10,
      category: "europeu",
      fk_idcategorys: 2,
      name_product: "Real /22",
      price: 224.99,
      image: "./images/produtos/real22.jpg",
      id_categorys: 2,
      name_categorys: "Clubes europeus",
      selected: false
    },
    {
      id_product: 11,
      category: "europeu",
      fk_idcategorys: 2,
      name_product: "Barcelona /22",
      price: 299.99,
      image: "./images/produtos/barcelona22.jpg",
      id_categorys: 2,
      name_categorys: "Clubes europeus",
      selected: false
    },
    {
      id_product: 6,
      category: "europeu",
      fk_idcategorys: 2,
      name_product: " Ajax /22",
      price: 269.99,
      image: "./images/produtos/ajax22.jpg",
      id_categorys: 2,
      name_categorys: "Clubes europeus",
      selected: false
    },
    {
      id_product: 7,
      category: "europeu",
      fk_idcategorys: 2,
      name_product: " Bayern /22",
      price: 299.99,
      image: "./images/produtos/bayern22.jpg",
      id_categorys: 2,
      name_categorys: "Clubes europeus",
      selected: false
    },
    {
      id_product: 3,
      category: "Retrô",
      fk_idcategorys: 3,
      name_product: "Brasil 1994",
      price: 139.60,
      image: "./images/produtos/brasil94.jpg",
      id_categorys: 3,
      name_categorys: "Camisas Retrô",
      selected: false,
    },
    {
      id_product: 5,
      category: "Retrô",
      fk_idcategorys: 3,
      name_product: "Argentina 1986",
      price: 119.60,
      image: "./images/produtos/argentinaretro.jpg",
      id_categorys: 3,
      name_categorys: "Camisas Retrô",
      selected: false,
    },
    {
      id_product: 8,
      category: "Retrô",
      fk_idcategorys: 3,
      name_product: "Itália 1982",
      price: 129.60,
      image: "./images/produtos/italiaretro.jpg",
      id_categorys: 3,
      name_categorys: "Camisas Retrô",
      selected: false,
    },
    {
      id_product: 12,
      category: "Retrô",
      fk_idcategorys: 3,
      name_product: "Alemanha 1990",
      price: 119.99,
      image: "./images/produtos/alemanha90.jpg",
      id_categorys: 3,
      name_categorys: "Camisas Retrô",
      selected: false,
    },
   
];

export default productsList;
